version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm --logevel=error install
  build:
    commands:
      - echo Build Phase
  post_build:
    commands:
      - echo PostBuild Phase
